environment: production
environmentCode:
name: ffc-iacs-namespace
namespace: ffc-iacs
workstream: ffc-iacs

labels: {}

containerSecret:
  name: ffc-iacs-container-secret
  type: Opaque

containerConfigMap:
  name: ffc-iacs-container-config

registrySecret:
 name: registry-credentials
 type: kubernetes.io/dockerconfigjson
 dockerConfigJson: ewogICJjcmVkc1N0b3JlIjogImRlc2t0b3AuZXhlIgp9

databaseConfigMap:
  name: db
  applicationsJdbcUrl: jdbc:not-real
  applicationsUser: applications
  applicationFormsJdbcUrl: jdbc:not-real
  applicationFormsUser: app_forms
  anomaliesJdbcUrl: jdbc:not-real
  anomaliesUser: anomalies
  cllJdbcUrl: jdbc:not-real
  cllUser: cll
  cropPlanJdbcUrl: jdbc:not-real
  cropPlanUser: cropplan
  dossiersJdbcUrl: jdbc:not-real
  dossiersUser: dossiers
  lauJdbcUrl: jdbc:not-real
  lauUser: lau
  lpisEditorJdbcUrl: jdbc:not-real
  lpisEditorUser: lpis_gis_server
  partyRegistryJdbcUrl: jdbc:not-real
  partyRegistryUser: party_registry
  printEngineJdbcUrl: jdbc:not-real
  printEngineUser: print_engine
  ssoJdbcUrl: jdbc:not-real
  ssoUser: sso2
  taskManagerJdbcUrl: jdbc:not-real
  taskManagerUser: taskmanager
  partiesAclJdbcUrl: jdbc:not-real
  partiesAclUser: parties_acl

databaseSecret:
  type: Opaque
  name: db-pwd
  applicationsPassword: not-real
  applicationFormsPassword: not-real
  anomaliesPassword: not-real
  cllPassword: not-real
  cropPlanPassword: not-real
  dossiersPassword: not-real
  lauPassword: not-real
  lpisEditorPassword: not-real
  partyRegistryPassword: not-real
  printEnginePassword: not-real
  ssoPassword: not-real
  taskManagerPassword: not-real
  partiesAclPassword: not-real

messageConfigMap:
  name: stateless-env
  sso2PublicKeyPath: /data/sso2_public_key
  timezone: Europe/London
  rmqHost: rabbitmq.rabbitmq.svc.cluster.local
  rmqPort: 5672
  rmqVHost: "/"
  rmqUser: not-real

messageSecret:
  type: Opaque
  name: stateless-pwd
  sso2TokensAuthSecret: not-real
  rmqPassword: not-real

persistentVolumeClaim:
  name: nfs
  storageClassName: ffc-iacs-storage-blob
  size: 1Pi # This value is ignored by the blob CSI driver but must be set to a value

deployPersistentVolume: true
