environment: production
environmentCode:
name: ffc-iacs-namespace
namespace: ffc-iacs
workstream: ffc-iacs

labels: {}

containerSecret:
  name: ffc-iacs-container-secret
  type: Opaque

containerConfigMap:
  name: ffc-iacs-container-config

registrySecret:
 name: ffc-iacs-registry-secret
 type: kubernetes.io/dockerconfigjson
 dockerConfigJson: ewogICJjcmVkc1N0b3JlIjogImRlc2t0b3AuZXhlIgp9

databaseConfigMap:
  name: ffc-iacs-database-config
  applicationsJdbcUrl: jdbc:tbc
  applicationsUser: applications
  applicationFormsJdbcUrl: jdbc:tbc
  applicationFormsUser: app_forms
  anomaliesJdbcUrl: jdbc:tbc
  anomaliesUser: anomalies
  cllJdbcUrl: jdbc:tbc
  cllUser: cll
  cropPlanJdbcUrl: jdbc:tbc
  cropPlanUser: cropplan
  dossiersJdbcUrl: jdbc:tbc
  dossiersUser: dossiers
  lauJdbcUrl: jdbc:tbc
  lauUser: lau
  lpisEditorJdbcUrl: jdbc:tbc
  lpisEditorUser: lpis_gis_server
  partyRegistryJdbcUrl: jdbc:tbc
  partyRegistryUser: party_registry
  printEngineJdbcUrl: jdbc:tbc
  printEngineUser: print_engine
  ssoJdbcUrl: jdbc:tbc
  ssoUser: sso2
  taskManagerJdbcUrl: jdbc:tbc
  taskManagerUser: taskmanager
  partiesAclJdbcUrl: jdbc:tbc
  partiesAclUser: parties_acl

databaseSecret:
  type: Opaque
  name: ffc-iacs-database-secret
  applicationsPassword: tbc
  applicationFormsPassword: tbc
  anomaliesPassword: tbc
  cllPassword: tbc
  cropPlanPassword: tbc
  dossiersPassword: tbc
  lauPassword: tbc
  lpisEditorPassword: tbc
  partyRegistryPassword: tbc
  printEnginePassword: tbc
  ssoPassword: tbc
  taskManagerPassword: tbc
  partiesAclPassword: tbc

messageConfigMap:
  name: ffc-iacs-message-config
  sso2PublicKeyPath: /data/sso2_public_key
  timezone: Europe/Rome
  rmqHost: rabbitmq.rabbitmq.svc.cluster.local
  rmqPort: 5672
  rmqVHost: iacs
  rmqUser: tbc

messageSecret:
  type: Opaque
  name: ffc-iacs-message-secret
  sso2TokensAuthSecret: tbc
  rmqPassword: tbc

serviceAccount:
  name: ffc-iacs-service-account
  automountServiceAccountToken: false

storageClass:
  name: ffc-iacs-storage-nfs

persistentVolume:
  name: ffc-iacs-persistent-volume
  size: 10Gi
  storageClassName: ffc-iacs-storage-nfs
  nfsPath: /tbc
  nfsServer: tbc
  nfsReadOnly: false

persistentVolumeClaim:
  name: ffc-iacs-persistent-volume-claim
  size: 10Gi
  volumeName: ffc-iacs-persistent-volume
