{{- include "ffc-helm-library.container-secret" (list . "ffc-iacs-namespace.database-secret") -}}
{{- define "ffc-iacs-namespace.database-secret" -}}
metadata:
  name: {{ .Values.databaseSecret.name | quote }}
type: {{ .Values.databaseSecret.type  | quote }}
data:
  DB_APPLICATIONS_PASSWORD: {{ .Values.databaseSecret.applicationsPassword | quote }}
  DB_APPLICATION_FORMS_PASSWORD: {{ .Values.databaseSecret.applicationFormsPassword | quote }}
  DB_ANOMALIES_PASSWORD: {{ .Values.databaseSecret.anomaliesPassword | quote }}
  DB_CLL_PASSWORD: {{ .Values.databaseSecret.cllPassword | quote }}
  DB_CROPPLAN_PASSWORD: {{ .Values.databaseSecret.cropPlanPassword | quote }}
  DB_DOSSIERS_PASSWORD: {{ .Values.databaseSecret.dossiersPassword | quote }}
  DB_LAU_PASSWORD: {{ .Values.databaseSecret.lauPassword | quote }}
  DB_LPIS_EDITOR_PASSWORD: {{ .Values.databaseSecret.lpisEditorPassword | quote }}
  DB_PARTY_REGISTRY_PASSWORD: {{ .Values.databaseSecret.partyRegistryPassword | quote }}
  DB_PRINTENGINE_PASSWORD: {{ .Values.databaseSecret.printEnginePassword | quote }}
  DB_SSO_PASSWORD: {{ .Values.databaseSecret.ssoPassword | quote }}
  DB_TASK_MANAGER_PASSWORD: {{ .Values.databaseSecret.taskManagerPassword | quote }}
  DB_PARTIES_ACL_PASSWORD: {{ .Values.databaseSecret.partiesAclPassword | quote }}
{{- end -}}
