{{- include "ffc-helm-library.container-secret" (list . "ffc-iacs-namespace.message-secret") -}}
{{- define "ffc-iacs-namespace.message-secret" -}}
metadata:
  name: {{ .Values.messageSecret.name | quote }}
type: {{ .Values.messageSecret.type  | quote }}
stringData:
  RMQ_PASSWORD: {{ .Values.messageSecret.rmqPassword | quote }}
{{- end -}}
