{{- include "ffc-helm-library.persistent-volume" (list . "ffc-iacs-namespace.persistent-volume") -}}
{{- define "ffc-iacs-namespace.persistent-volume" -}}
spec:
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.persistentVolume.nfsPath }}
    server: {{ .Values.persistentVolume.nfsServer }}
    readOnly: {{ .Values.persistentVolume.nfsReadOnly }}
  mountOptions:
    - vers=4.1
  claimRef:
    name: {{ .Values.persistentVolumeClaim.name }}
{{- end -}}
