{{- if .Values.deployPersistentVolume -}}
{{- include "ffc-helm-library.persistent-volume-claim" (list . "ffc-iacs-namespace.persistent-volume-claim") -}}
{{- end -}}
{{- define "ffc-iacs-namespace.persistent-volume-claim" -}}
metadata:
  {{- if and (.Values.environmentCode) (ne (.Values.environmentCode | toString ) "snd") }}
  name: {{ .Values.persistentVolumeClaim.name }}-{{ .Values.namespace }}-{{ .Values.environmentCode }}
  {{ else }}
  name: {{ .Values.persistentVolumeClaim.name }}-{{ .Values.namespace }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ .Values.persistentVolume.name }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
{{- end -}}
