{{- if .Values.deployPersistentVolume -}}
{{- include "ffc-helm-library.persistent-volume" (list . "ffc-iacs-namespace.persistent-volume") -}}
{{- end -}}
{{- define "ffc-iacs-namespace.persistent-volume" -}}
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: {{ .Values.persistentVolume.provisionedBy }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  csi:
    driver: {{ .Values.persistentVolume.provisionedBy }}
    readOnly: {{ .Values.persistentVolume.readOnly }}
    volumeHandle: {{ .Values.persistentVolume.handle }}-{{ .Values.namespace }}
    volumeAttributes:
      resourceGroup: {{ .Values.persistentVolume.resourceGroup }}
      storageAccount: {{ .Values.persistentVolume.storageAccount }}
      containerName: {{ .Values.persistentVolume.containerName }}
      protocol: {{ .Values.persistentVolume.protocol }}
{{- end -}}
