{{- include "ffc-helm-library.persistent-volume-claim" (list . "ffc-iacs-namespace.persistent-volume-claim") -}}
{{- define "ffc-iacs-namespace.persistent-volume-claim" -}}
spec:
  accessModes:
    - ReadWriteMany
{{- end -}}
