{{- include "ffc-helm-library.container-secret" (list . "ffc-iacs-namespace.registry-secret") -}}
{{- define "ffc-iacs-namespace.registry-secret" -}}
metadata:
  name: {{ .Values.registrySecret.name | quote }}
type: {{ .Values.registrySecret.type  | quote }}
data:
  .dockerconfigjson: {{ .Values.registrySecret.dockerConfigJson }}
{{- end -}}
