{{- include "ffc-helm-library.service-account" (list . "ffc-iacs-namespace.service-account") -}}
{{- define "ffc-iacs-namespace.service-account" -}}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
  imagePullSecrets:
    - name: {{ .Values.registrySecret.name }}
{{- end -}}
